import type { IntroOption } from "@/features/intro-options/model";

export const introOptions: IntroOption[] = [
  {
    key: "INTRO-APP-01",
    category: "application",
    title: "果汁标签侦探",
    score: 96,
    concept: "三瓶外观相近的果汁只留下了部分配料标签，学生需要找出哪一瓶更适合分享。",
    hook: "同样大小的瓶子，为什么标签上的数字完全不同？",
    medium: "短视频",
    duration: 55,
    courseAnchor: "比较三瓶果汁中果汁含量占整瓶容量的关系。",
    firstQuestion: "只看这些数字，我们怎样公平地比较三瓶果汁？",
    handoff: "三张标签并排出现，人物停下选择，等待课堂讨论。",
    mustNotPreteach: ["百分数定义", "分数化成百分数的方法"],
    reason: "生活任务明确，数据易观察，能自然产生统一比较标准的需要。",
  },
  {
    key: "INTRO-SCI-01",
    category: "science",
    title: "会变色的百格窗",
    score: 93,
    concept: "一扇由一百块小玻璃组成的窗户会随光线逐格变色，清晨与正午呈现不同图案。",
    hook: "窗户明明没有变大，亮起来的部分为什么看上去差别这么大？",
    medium: "视频",
    duration: 45,
    courseAnchor: "把亮起的小格数量与一百格整体建立唯一联系。",
    firstQuestion: "怎样用一个数准确说出亮起部分占整扇窗的多少？",
    handoff: "镜头定格在 37 格亮起的完整百格窗。",
    mustNotPreteach: ["百分号读写", "百分数意义结论"],
    reason: "百格结构直观，视觉吸引力强，制作成本适中。",
  },
  {
    key: "INTRO-STO-01",
    category: "story",
    title: "失而复得的航海图",
    score: 89,
    concept: "一张破损航海图被分成一百个小格，修复师每天只能补回其中一部分。",
    hook: "只找到 62 个碎片时，航海图算修复到什么程度？",
    medium: "图片 + 提问",
    duration: 50,
    courseAnchor: "用已修复格数和总格数之间的关系描述修复进度。",
    firstQuestion: "怎样让所有人一眼看懂航海图修复了多少？",
    handoff: "最后一块已找到碎片被放回，仍有空缺等待统计。",
    mustNotPreteach: ["百分数定义", "百分数大小比较规则"],
    reason: "故事目标清楚，进度表达与百分数关系自然。",
  },
  {
    key: "INTRO-APP-02",
    category: "application",
    title: "运动会座位选择",
    score: 86,
    concept: "两个看台开放座位数不同，班级需要选择空座比例更高的一侧。",
    hook: "甲看台空 30 个座位，乙看台空 25 个，应该去哪边？",
    medium: "提问",
    duration: 40,
    courseAnchor: "比较空座数占各自看台总座位的关系。",
    firstQuestion: "只比较空座个数公平吗？还需要知道什么？",
    handoff: "两张看台示意图和空座数据同时出现。",
    mustNotPreteach: ["百分数比较方法"],
    reason: "比较冲突自然，能暴露只看部分量的错误。",
  },
  {
    key: "INTRO-SCI-02",
    category: "science",
    title: "云层覆盖实验",
    score: 84,
    concept: "卫星每隔十分钟拍摄同一片天空，云层逐渐遮住画面。",
    hook: "怎样描述云层究竟遮住了多少天空？",
    medium: "图片",
    duration: 35,
    courseAnchor: "把图像划分为一百个等大区域观察覆盖关系。",
    firstQuestion: "用什么方式能方便比较不同时刻的云量？",
    handoff: "三幅不同时刻的天空图并排定格。",
    mustNotPreteach: ["百分数定义"],
    reason: "科学观察感强，适合用图像建立整体与部分关系。",
  },
  {
    key: "INTRO-STO-02",
    category: "story",
    title: "灯塔守望者",
    score: 81,
    concept: "守望者要在天黑前点亮海湾边一百盏引航灯，但一阵风吹灭了其中一部分。",
    hook: "还亮着多少，才能让船员快速判断航道是否安全？",
    medium: "表演",
    duration: 60,
    courseAnchor: "用亮灯数占全部灯数的关系表达当前状态。",
    firstQuestion: "怎样把亮灯情况告诉远处的船员最清楚？",
    handoff: "守望者举起记录板，等待填写。",
    mustNotPreteach: ["百分号", "百分数写法"],
    reason: "信息传达目标明确，适合课堂口头参与。",
  },
  {
    key: "INTRO-APP-03",
    category: "application",
    title: "班级阅读挑战",
    score: 78,
    concept: "三个小组人数不同，要比较各组本周完成阅读计划的情况。",
    hook: "完成 8 人的小组一定比完成 7 人的小组表现好吗？",
    medium: "实物 + 提问",
    duration: 45,
    courseAnchor: "比较完成人数占小组总人数的关系。",
    firstQuestion: "怎样消除小组人数不同带来的影响？",
    handoff: "三组人数和完成人数同时写在板上。",
    mustNotPreteach: ["求百分率公式"],
    reason: "贴近班级生活，但需要教师注意避免排名压力。",
  },
  {
    key: "INTRO-SCI-03",
    category: "science",
    title: "种子发芽记录",
    score: 75,
    concept: "同样数量的种子在不同环境中发芽数量不同，观察员需要记录结果。",
    hook: "一盘发芽 18 粒，另一盘发芽 24 粒，哪种环境更合适？",
    medium: "实物",
    duration: 50,
    courseAnchor: "把发芽数量放回各自种子总数中比较。",
    firstQuestion: "总数不同时，怎样比较发芽情况？",
    handoff: "两盘种子和记录卡放在观察台上。",
    mustNotPreteach: ["百分率计算公式"],
    reason: "数据真实，可与科学观察连接，但准备实物成本较高。",
  },
  {
    key: "INTRO-STO-03",
    category: "story",
    title: "拼图店的承诺",
    score: 72,
    concept: "拼图店承诺找回每盒丢失的拼块，两个孩子拿来的拼图大小不同。",
    hook: "都找回 12 块，为什么完成程度不一样？",
    medium: "图片",
    duration: 45,
    courseAnchor: "比较找回拼块数占各自整盒拼图的关系。",
    firstQuestion: "怎样描述每盒拼图已经找回了多少？",
    handoff: "两盒拼图留下不同数量的空位。",
    mustNotPreteach: ["百分数定义", "通分方法"],
    reason: "故事简洁，比较需要明确，但视觉新颖度一般。",
  },
];

const independentOptionSeeds = [
  {
    title: "生活线索观察站",
    concept: "几个外观相近的生活物品带着不同线索出现，人物需要先观察，再决定怎样比较。",
    hook: "看起来差不多的东西，为什么会让人得到不同判断？",
  },
  {
    title: "会变化的数学画面",
    concept: "同一幅画面在三个时刻发生变化，学生需要找出始终不变和真正改变的部分。",
    hook: "画面一直在变，哪条线索最值得先抓住？",
  },
  {
    title: "教室里的小侦探",
    concept: "一张信息不完整的记录卡出现在教室里，人物通过补线索逐步排除错误判断。",
    hook: "只凭眼前这条线索，真的能下结论吗？",
  },
  {
    title: "一步一步找规律",
    concept: "连续出现的几个动作或图形留下可观察的变化，最后一个位置故意空下来。",
    hook: "下一步会发生什么，你的理由来自哪里？",
  },
  {
    title: "同桌观点交换局",
    concept: "两名学生面对同一画面给出不同解释，双方都展示一条看似合理的依据。",
    hook: "两个答案都有道理时，我们该先检查什么？",
  },
  {
    title: "错误答案诊断室",
    concept: "一个常见但不完整的答案先出现，人物通过操作和对照发现它遗漏了重要条件。",
    hook: "这个答案哪里让你觉得不太对？",
  },
  {
    title: "校园任务挑战",
    concept: "班级接到一个需要分工、记录和判断的校园任务，关键信息分散在不同位置。",
    hook: "怎样整理这些信息，才能让全班快速做出判断？",
  },
  {
    title: "图形线索实验室",
    concept: "几张可移动的图形卡在操作台上被翻转、拼合和比较，关系在动作中逐步显现。",
    hook: "只改变摆放方式，原来的关系会不会改变？",
  },
  {
    title: "最后一块拼图",
    concept: "一幅接近完成的拼图只缺最后一块，人物需要根据周围线索判断它应当是什么。",
    hook: "没有看到最后一块，我们能不能先判断它的样子？",
  },
];

export function createTopicIntroOptions(knowledgePoint: string): IntroOption[] {
  const topic = knowledgePoint.trim() || "本课知识点";
  return introOptions.map((option, index) => {
    const seed = independentOptionSeeds[index];
    return {
      ...option,
      concept: seed?.concept ?? option.concept,
      courseAnchor: `回到${topic}的教材情境，组织学生比较不同发现并说明判断依据。`,
      firstQuestion: `你先观察到了什么？这些线索和${topic}可能有什么关系？`,
      handoff: `画面停在与${topic}有关的关键线索上，不给出结论，等待学生交流。`,
      hook: seed?.hook ?? option.hook,
      mustNotPreteach: [`${topic}的完整结论`, `${topic}的固定解法`],
      reason: `独立创意不预设课程结论；锚定后与${topic}直接相关，并保留学生观察、表达和验证的空间。`,
      title: seed?.title ?? `课堂导入方案 ${String(index + 1)}`,
    };
  });
}
