"""stage0 project upload and job models

Revision ID: 8dffee7f47f1
Revises:
Create Date: 2026-07-17 05:05:40.737970
"""

from collections.abc import Sequence
from datetime import UTC, datetime
from uuid import UUID

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "8dffee7f47f1"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('active', 'disabled')", name=op.f("ck_organizations_status_allowed")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
        sa.UniqueConstraint("slug", name=op.f("uq_organizations_slug")),
    )
    op.create_table(
        "file_assets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("asset_key", sa.String(length=255), nullable=False),
        sa.Column("asset_kind", sa.String(length=80), nullable=False),
        sa.Column("current_version_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("retention_class", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("updated_by", sa.Uuid(), nullable=False),
        sa.Column("lock_version", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'active', 'rejected')",
            name=op.f("ck_file_assets_status_allowed"),
        ),
        sa.CheckConstraint("lock_version >= 1", name=op.f("ck_file_assets_lock_version_positive")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_file_assets_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_file_assets")),
    )
    op.create_index(
        "uq_file_assets_organization_asset_key_active",
        "file_assets",
        ["organization_id", "asset_key"],
        unique=True,
        postgresql_where="deleted_at IS NULL",
    )
    op.create_table(
        "principals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("principal_type", sa.String(length=20), nullable=False),
        sa.Column("display_name", sa.String(length=160), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("principal_type IN ('system')", name=op.f("ck_principals_type_allowed")),
        sa.CheckConstraint(
            "status IN ('active', 'disabled')", name=op.f("ck_principals_status_allowed")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_principals_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_principals")),
    )
    op.create_index(
        op.f("ix_principals_organization_id"), "principals", ["organization_id"], unique=False
    )
    seeded_at = datetime(2026, 7, 17, tzinfo=UTC)
    op.bulk_insert(
        sa.table(
            "organizations",
            sa.column("id", sa.Uuid()),
            sa.column("slug", sa.String()),
            sa.column("name", sa.String()),
            sa.column("status", sa.String()),
            sa.column("created_at", sa.DateTime(timezone=True)),
        ),
        [
            {
                "id": UUID("01900000-0000-7000-8000-000000000001"),
                "slug": "system",
                "name": "ShanHaiEdu System",
                "status": "active",
                "created_at": seeded_at,
            }
        ],
    )
    op.bulk_insert(
        sa.table(
            "principals",
            sa.column("id", sa.Uuid()),
            sa.column("organization_id", sa.Uuid()),
            sa.column("principal_type", sa.String()),
            sa.column("display_name", sa.String()),
            sa.column("status", sa.String()),
            sa.column("created_at", sa.DateTime(timezone=True)),
        ),
        [
            {
                "id": UUID("01900000-0000-7000-8000-000000000002"),
                "organization_id": UUID("01900000-0000-7000-8000-000000000001"),
                "principal_type": "system",
                "display_name": "ShanHaiEdu System",
                "status": "active",
                "created_at": seeded_at,
            }
        ],
    )
    op.create_table(
        "file_asset_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("file_asset_id", sa.Uuid(), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("storage_bucket", sa.String(length=63), nullable=False),
        sa.Column("storage_key", sa.String(length=1024), nullable=False),
        sa.Column("mime_type", sa.String(length=255), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("etag", sa.String(length=255), nullable=False),
        sa.Column("scan_status", sa.String(length=20), nullable=False),
        sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "scan_status IN ('pending', 'clean', 'rejected')",
            name=op.f("ck_file_asset_versions_scan_status_allowed"),
        ),
        sa.CheckConstraint(
            "byte_size >= 0", name=op.f("ck_file_asset_versions_byte_size_nonnegative")
        ),
        sa.CheckConstraint("version_no > 0", name=op.f("ck_file_asset_versions_version_positive")),
        sa.ForeignKeyConstraint(
            ["file_asset_id"],
            ["file_assets.id"],
            name=op.f("fk_file_asset_versions_file_asset_id_file_assets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_file_asset_versions_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_file_asset_versions")),
    )
    op.create_index(
        "uq_file_asset_versions_asset_version",
        "file_asset_versions",
        ["file_asset_id", "version_no"],
        unique=True,
    )
    op.create_index(
        "uq_file_asset_versions_storage_object",
        "file_asset_versions",
        ["storage_bucket", "storage_key"],
        unique=True,
    )
    op.create_foreign_key(
        "fk_file_assets_current_version_id_file_asset_versions",
        "file_assets",
        "file_asset_versions",
        ["current_version_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_no", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("subject", sa.String(length=40), nullable=False),
        sa.Column("school_stage", sa.String(length=40), nullable=False),
        sa.Column("grade", sa.String(length=40), nullable=True),
        sa.Column("textbook_edition", sa.String(length=120), nullable=True),
        sa.Column("knowledge_point", sa.String(length=255), nullable=False),
        sa.Column("default_language", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("automation_mode", sa.String(length=20), nullable=False),
        sa.Column("owner_principal_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("updated_by", sa.Uuid(), nullable=False),
        sa.Column("lock_version", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "automation_mode IN ('manual', 'assisted', 'automatic')",
            name=op.f("ck_projects_automation_mode_allowed"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'active', 'archived')", name=op.f("ck_projects_status_allowed")
        ),
        sa.CheckConstraint(
            "subject = 'primary_math'", name=op.f("ck_projects_subject_primary_math")
        ),
        sa.CheckConstraint("lock_version >= 1", name=op.f("ck_projects_lock_version_positive")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_projects_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owner_principal_id"],
            ["principals.id"],
            name=op.f("fk_projects_owner_principal_id_principals"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )
    op.create_index(
        "ix_projects_organization_created",
        "projects",
        ["organization_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "uq_projects_organization_project_no_active",
        "projects",
        ["organization_id", "project_no"],
        unique=True,
        postgresql_where="deleted_at IS NULL",
    )
    op.create_table(
        "source_materials",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("material_kind", sa.String(length=40), nullable=False),
        sa.Column("file_asset_id", sa.Uuid(), nullable=True),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=255), nullable=False),
        sa.Column("upload_status", sa.String(length=30), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confirmed_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("updated_by", sa.Uuid(), nullable=False),
        sa.Column("lock_version", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "upload_status IN ('pending_upload', 'confirmed', 'rejected')",
            name=op.f("ck_source_materials_upload_status_allowed"),
        ),
        sa.CheckConstraint(
            "lock_version >= 1", name=op.f("ck_source_materials_lock_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_source_materials_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_source_materials_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["file_asset_id"],
            ["file_assets.id"],
            name=op.f("fk_source_materials_file_asset_id_file_assets"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_materials")),
    )
    op.create_index(
        "ix_source_materials_organization_project",
        "source_materials",
        ["organization_id", "project_id"],
        unique=False,
    )
    op.create_table(
        "generation_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("source_material_id", sa.Uuid(), nullable=True),
        sa.Column("job_type", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("progress_percent", sa.Integer(), nullable=False),
        sa.Column("progress_message", sa.String(length=500), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("idempotency_key", sa.String(length=128), nullable=True),
        sa.Column("request_hash", sa.String(length=64), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("cancel_requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("updated_by", sa.Uuid(), nullable=False),
        sa.Column("lock_version", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('created', 'queued', 'running', 'succeeded', 'failed', "
            "'cancel_requested', 'cancelled')",
            name=op.f("ck_generation_jobs_status_allowed"),
        ),
        sa.CheckConstraint(
            "lock_version >= 1", name=op.f("ck_generation_jobs_lock_version_positive")
        ),
        sa.CheckConstraint("priority >= 0", name=op.f("ck_generation_jobs_priority_nonnegative")),
        sa.CheckConstraint(
            "progress_percent BETWEEN 0 AND 100", name=op.f("ck_generation_jobs_progress_range")
        ),
        sa.CheckConstraint(
            "project_id IS NOT NULL OR source_material_id IS NOT NULL",
            name=op.f("ck_generation_jobs_stage0_source_present"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_generation_jobs_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_generation_jobs_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_material_id"],
            ["source_materials.id"],
            name=op.f("fk_generation_jobs_source_material_id_source_materials"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_generation_jobs")),
    )
    op.create_index(
        "ix_generation_jobs_organization_status_created",
        "generation_jobs",
        ["organization_id", "status", "created_at"],
        unique=False,
    )
    op.create_table(
        "upload_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("material_id", sa.Uuid(), nullable=False),
        sa.Column("storage_bucket", sa.String(length=63), nullable=False),
        sa.Column("storage_key", sa.String(length=1024), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("expected_media_type", sa.String(length=255), nullable=False),
        sa.Column("expected_size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("expected_sha256", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("updated_by", sa.Uuid(), nullable=False),
        sa.Column("lock_version", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('created', 'confirmed', 'expired', 'rejected')",
            name=op.f("ck_upload_sessions_status_allowed"),
        ),
        sa.CheckConstraint(
            "expected_size_bytes > 0", name=op.f("ck_upload_sessions_size_positive")
        ),
        sa.CheckConstraint(
            "lock_version >= 1", name=op.f("ck_upload_sessions_lock_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["source_materials.id"],
            name=op.f("fk_upload_sessions_material_id_source_materials"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_upload_sessions_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_upload_sessions_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_upload_sessions")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_upload_sessions_storage_key")),
    )
    op.create_index(
        "ix_upload_sessions_organization_project",
        "upload_sessions",
        ["organization_id", "project_id"],
        unique=False,
    )
    op.create_index(
        "ix_upload_sessions_status_expires",
        "upload_sessions",
        ["status", "expires_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_upload_sessions_status_expires", table_name="upload_sessions")
    op.drop_index("ix_upload_sessions_organization_project", table_name="upload_sessions")
    op.drop_table("upload_sessions")
    op.drop_index("ix_generation_jobs_organization_status_created", table_name="generation_jobs")
    op.drop_table("generation_jobs")
    op.drop_index("ix_source_materials_organization_project", table_name="source_materials")
    op.drop_table("source_materials")
    op.drop_index(
        "uq_projects_organization_project_no_active",
        table_name="projects",
        postgresql_where="deleted_at IS NULL",
    )
    op.drop_index("ix_projects_organization_created", table_name="projects")
    op.drop_table("projects")
    op.drop_constraint(
        "fk_file_assets_current_version_id_file_asset_versions",
        "file_assets",
        type_="foreignkey",
    )
    op.drop_index("uq_file_asset_versions_storage_object", table_name="file_asset_versions")
    op.drop_index("uq_file_asset_versions_asset_version", table_name="file_asset_versions")
    op.drop_table("file_asset_versions")
    op.drop_index(
        "uq_file_assets_organization_asset_key_active",
        table_name="file_assets",
        postgresql_where="deleted_at IS NULL",
    )
    op.drop_table("file_assets")
    op.drop_index(op.f("ix_principals_organization_id"), table_name="principals")
    op.drop_table("principals")
    op.drop_table("organizations")
    # ### end Alembic commands ###
